name: Tests
on:
  push:
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    name: Python Tests
    container:
      image: python:3.7-buster
    steps:
      - name: Clone repo
        uses: actions/checkout@v2
      - name: Run the Python Tests
        run: |
            # This configures the test stuff
            echo "127.0.0.1 db localhost" | sudo tee -a /etc/hosts
            apt-get update -qy
            apt-get install -y python-dev python-pip
            pip install -r requirements.txt
            python manage.py migrate
            python manage.py test
            coverage run --source='.' manage.py test
            coverage report -m
            coverage-badge

  hawkscan:
    name: StackHawk DAST
    runs-on: ubuntu-latest
    steps:
      name: StackHawk DAST
      runs-on: ubuntu-latest
      steps:
        - name: Clone repo
          uses: actions/checkout@v2
        - name: Run the Vuln Django Containers
          run: docker-compose up -d
        - name: Run HawkScan
          uses: stackhawk/hawkscan-action@v1.2.1
          with:
            apiKey: ${{ secrets.HAWK_API_KEY }}
            configurationFiles: stackhawk.yml stackhawk-github.yml
            network: vuln_django_play_default
