name: Tests
on:
  push:
  pull_request: {}
jobs:
  test:
    runs-on: ubuntu-latest
    name: Python Tests
    steps:
      - name: Clone repo
        uses: actions/checkout@v2
      - name: Start Database
        run: docker-compose up -d db
      - name: Run the Python Tests
        run: |
            # This configures the test stuff
            echo "127.0.0.1 db localhost" | sudo tee -a /etc/hosts
            sudo apt-get update -qy
            sudo apt-get install -y python3-dev python3-pip
            pip install pipenv
            pipenv install --system --deploy
            python3 manage.py migrate
            python3 manage.py test
            coverage run --source='.' manage.py test
            coverage report -m
            coverage-badge

  hawkscan:
    name: StackHawk DAST
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v2
      - name: Run the Vuln Django Containers
        run: docker-compose up -d
      - name: Run HawkScan
        uses: stackhawk/hawkscan-action@4c3258cd62248dac6d9fe91dd8d45928c697dee0
        continue-on-error: false
        with:
          apiKey: ${{ secrets.HAWK_API_KEY }}
          configurationFiles: stackhawk.yml stackhawk-github.yml
          network: vulny_django_default
          codeScanningAlerts: true
          githubToken: ${{ github.token }}

  semgrep:
    name: Semgrep Scan
    runs-on: ubuntu-latest
    if: (github.actor != 'dependabot[bot]')
    steps:
      - uses: actions/checkout@v2
      - uses: returntocorp/semgrep-action@v1
        with:
          publishToken: ${{ secrets.SEMGREP_APP_TOKEN }}
          generateSarif: "1"
      - name: Upload SARIF file for GitHub Advanced Security Dashboard
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: semgrep.sarif
        if: always()
