name: Tests
on:
  push:
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    name: Python Tests
    steps:
      - name: Clone repo
        uses: actions/checkout@v2
      - name: Start Database
        run: docker-compose up -d db
      - name: Run the Python Tests
        run: |
            # This configures the test stuff
            echo "127.0.0.1 db localhost" | sudo tee -a /etc/hosts
            sudo apt-get update -qy
            sudo apt-get install -y python3-dev python3-pip
            pip install pipenv
            pipenv install --system --deploy
            python3 manage.py migrate
            python3 manage.py test
            coverage run --source='.' manage.py test
            coverage report -m
            coverage-badge

  hawkscan:
    name: StackHawk DAST
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v2
      - name: Run the Vuln Django Containers
        run: docker-compose up -d
      - name: Run HawkScan
        uses: stackhawk/hawkscan-action@4c3258cd62248dac6d9fe91dd8d45928c697dee0
        continue-on-error: false
        with:
          apiKey: ${{ secrets.HAWK_API_KEY }}
          configurationFiles: stackhawk.yml stackhawk-github.yml
          network: vulny_django_default
          codeScanningAlerts: true
          githubToken: ${{ github.token }}

  NextGen-Static-Analysis:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Download ShiftLeft CLI
      run: |
        curl https://cdn.shiftleft.io/download/sl > ${GITHUB_WORKSPACE}/sl && chmod a+rx ${GITHUB_WORKSPACE}/sl && curl https://raw.githubusercontent.com/ShiftLeftSecurity/field-integrations/master/shiftleft-utils/export.py > ${GITHUB_WORKSPACE}/export.py && curl https://raw.githubusercontent.com/ShiftLeftSecurity/field-integrations/master/shiftleft-utils/requirements.txt > ${GITHUB_WORKSPACE}/requirements.txt && curl https://raw.githubusercontent.com/ShiftLeftSecurity/field-integrations/master/shiftleft-utils/common.py > ${GITHUB_WORKSPACE}/common.py && curl https://raw.githubusercontent.com/ShiftLeftSecurity/field-integrations/master/shiftleft-utils/config.py > ${GITHUB_WORKSPACE}/config.py
    # ShiftLeft requires Java 1.8. Post the package step override the version
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - run: pip3 install -r ${GITHUB_WORKSPACE}/requirements.txt && pip3 install config pyjwt
    - name: NextGen Static Analysis
      run: ${GITHUB_WORKSPACE}/sl analyze --wait --app vulny_django --tag branch=${{ github.head_ref }} --python && python ${GITHUB_WORKSPACE}/export.py -a vulny_django -f sarif -o ${GITHUB_WORKSPACE}/sarif_report.sarif
      env:
        SHIFTLEFT_ACCESS_TOKEN: ${{ secrets.SHIFTLEFT_ACCESS_TOKEN }}
        GITHUB_TOKEN: ${{ github.token }}
    - name: Upload SARIF
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: ${GITHUB_WORKSPACE}/sarif_report.sarif
#    - name: Upload report
#      uses: github/codeql-action/upload-sarif@v1
#      with:
#        sarif_file: reports
